# This is an example config.
# !!! DO NOT COMMIT REAL CONFIGS TO PUBLIC REPOSITORIES !!!
databases:
  plug:
    type: plug
  postgreSQL:
    type: postgreSQL
    host: localhost
    port: 5432
    user: user
    password: pass
    dbname: logs
    scripts:
      insert: ""
      staging_logs: ""
      table: ""
      views: ""

settings:
  database: plug
  view: cli #cli or gui
  parser: default #default of plug
