# This is an example config.
# !!! DO NOT COMMIT REAL CONFIGS TO PUBLIC REPOSITORIES !!!
databases:
  plug:
    type: plug
  postgreSQL:
    type: postgreSQL
    host: localhost
    port: 5432
    username: user
    password: pass
    database: logs


settings:
  database: plug
  view: gui #cli or gui
  parser: default
